### ISSUE TITLE
Empty dataset

### ISSUE THREAD

**Issue by demolnau** [DRL/blobtools#102]
I have an assembly from Spades that for some reason will not create a dataset with blobtools2. I tried out my code with an organism that was already assembled and on ncbi and didn't have any trouble. So you have any idea why this genome from a Spades assembly won't play nice? 
I am throwing a little bit of of the fasta sequence below to show the format. 
>NODE_1_length_3471173_cov_2.719110
AAGTTAAATTAAAAATTTATTTAAAAAAAAAAAAAATAATAATAATAATAATAATAATAA
TTACAAGTACAGGATAATATAAGAATAAGATATTGAAATTGATTGGATATTTTATGCAAG
TTTTAATAGCAGTGACTCGATAATTATTTTACAATATTATGTCTGTAATTTGATAAAAAT
GATGGAATAAAAAATTATTAAGAAAAAATTTCTTCTCTTTTTAAATCTCTACCTTCAATG
ATATTACTTGTTAAATATTTGGTTATAGTATCGATTGAATATCAAGTCAGAACACGTAGC
GGGATAATATATCCACGAGGATTACCAAACAATGTACAGCAATTTCAAAACATTCCAATA
ACATCAATAAAAAAATAGTTCAACACCGTAGTAAAAATTATAGCGATCCCACTTCAATCT ...

Code:
/home/demolnau/work/blobtoolkit/blobtools2/blobtools create \ 
    --fasta /home/demolnau/work/pego_contaminants/pego_scaffolds_30X.fa \ 
    --meta /home/demolnau/work/pego_contaminants/pego_scaffolds_30X.yaml \ 
    --taxdump /home/demolnau/work/blobtoolkit/taxdump \ 
    /home/demolnau/work/pego_contaminants/datasets/pegoscapus_spades_assembly_30X

Please send help!

**Comment by DRL** [comment]
Hi demolnau,

different blobtools, you want to ask here: https://github.com/blobtoolkit/blobtools2/issues

cheers,

dom
