### ISSUE TITLE
list object has no attribute values

### ISSUE THREAD

**Issue by demolnau** [DRL/blobtools#105]
So I am trying to use bestsum as the taxrule and use the command below:

`
/home/demolnau/work/blobtoolkit/blobtools2/blobtools add \
--hits pegoscapus_spades_30X.ncbi.blastn.out \
--hits pegoscapus_scaffolds.diamond.blastx.out \
--hits pegoscapus_against_ceratosolen_solmsi.ncbi.blastn.out \
--hits pegoscapus_against_nasonia_vitripennis.ncbi.blastn.out \
--hits-cols 1=qseqid,2=sseqid,3=pident,4=length,5=mismatch,6=gapopen,7=qstart,8=qend,9=sstart,10=send,11=evalue,12=bitscore,13=staxids \
--taxrule bestsum \
--taxdump /home/demolnau/work/blobtoolkit/taxdump/  \
--replace \
 /home/demolnau/work/pego_contaminants/datasets/pegoscapus_spades_assembly_30X/
`

and I keep getting this error

`
Loading parsed taxdump
bestsum
Traceback (most recent call last):
  File "/home/demolnau/work/blobtoolkit/blobtools2/lib/add.py", line 165, in <module>
    main()
  File "/home/demolnau/work/blobtoolkit/blobtools2/lib/add.py", line 132, in main
    meta=meta)
  File "/work/LAS4/jnason-lab/demolnau/blobtoolkit/blobtools2/lib/hits.py", line 311, in parse
    identifiers)
  File "/work/LAS4/jnason-lab/demolnau/blobtoolkit/blobtools2/lib/hits.py", line 71, in apply_taxrule
    blank = [None] * len(identifiers.values)
AttributeError: 'list' object has no attribute 'values'
`

I thought this meant that the taxids were empty and I went back and altered the blast files so the taxids for the local hits gave an actual taxid numbers instead of N/A, but I am still getting this error so I am assuming I am missing a field somewhere.  When I search my files, there aren't any N/A columns. Am I missing an argument or is something in the wrong order?

**Comment by DRL** [comment]
Hi demolnau, 

different `blobtools`, you want to ask here: https://github.com/blobtoolkit/blobtools2/issues

cheers, 

dom
