### ISSUE TITLE
CONCOCT

### ISSUE THREAD

**Issue by sarah872** [DRL/blobtools#106]
Could you give some example code of how to use the coverage & taxonomy files from `blobtools view --concoct` with CONCOCT?

**Comment by DRL** [comment]
Hi sarah872,

i have never actually used it and was just asked to write an output function for a user.

I assume more information can be found here: https://concoct.readthedocs.io/en/latest/

But YMMV as it could also be that this format is no longer accepted by the latest version of CONCOCT.

cheers, 

dom
