### ISSUE TITLE
blobtools Create doing nothing

### ISSUE THREAD

**Issue by Lamm-a** [DRL/blobtools#109]
I am trying to run blobtools Create but nothing seems to happen. I ran it for 2 hours with 5 cores and 20G memory and the only std output was:

`^M[%] :   0%|                                                                                                                                                                 | 0.00/64.0 [00:00<?, ?it/s]^M[%] : 100%|█`

Is this normal and should I just increase the run time?

**Comment by DRL** [comment]
Hi, 

That doesn't look good. What's the command you are running? 

cheers, 

dom

**Comment by Lamm-a** [comment]
Hi, sorry i forgot to include it initially:

`blobtools create -i $assembly -b $bam -t $outdir/${prefix}.out -o "$prefix" --nodes path/to/data/nodes.dmp --names path/to/data/names.dmp`

**Comment by Lamm-a** [comment]
@DRL Hi Dom,

Any idea what is going on here? Do I just need to give it more time?

Cheers

**Comment by DRL** [comment]
I mean hard to say...

Can you post the actual command you ran and the whole output?

Something went wrong and that has to do with the input files.

You need to tell me more about the input files...

cheers. 

dom

**Comment by Lamm-a** [comment]
@DRL 
Hi Dom

Here is the input:

```
samtools index $bam

cd $outdir

blobtools create -i $assembly -b $bam -t $outdir/${prefix}.out -o "$prefix" --nodes /home/lamma/faststorage/scripts/qc_and_filtering/data/nodes.dmp --names /home/lamma/faststorage/scripts/qc_and_filtering/data/names.dmp
```

Here is the output in full:
[PSU4_ISF1A.zip](https://github.com/DRL/blobtools/files/5525266/PSU4_ISF1A.zip)

Here is the input file:
[PSU4_ISF1A_nextPolish.zip](https://github.com/DRL/blobtools/files/5525275/PSU4_ISF1A_nextPolish.zip)


Cheers
Lamma

**Comment by DRL** [comment]
ok, so you have:
- an assembly (PSU4_ISF1A_nextPolish.zip) 
- a BLAST file (PSU4_ISF1A.zip)

and your BAM file is sorted by readnames?

**Comment by DRL** [comment]
also, how did you map the reads? did you use `bwa mem`?

**Comment by Lamm-a** [comment]
Yes it was just aligned to `PSU4_ISF1A_nextPolish.fasta` via `bwa mem`.

**Comment by DRL** [comment]
could you run the `blobtools create` command again and post the output it prints to screen?

**Comment by Lamm-a** [comment]
I am running inside a slurm job but the content of the orignal post is what I see in the .out of the slurm job so what should be what I see if I did it on the command line I think.

**Comment by DRL** [comment]
was there no `.err` file?

**Comment by Lamm-a** [comment]
Nope, not from what I can see

**Comment by Lamm-a** [comment]
Okay when running on the command line I just a much more realistic output:

```
[+] Parsing FASTA - /home/lamma/faststorage/kasun_amyco/nextPolish-ouput/PSU4_ISF1A/genome.nextpolish.fasta
[+] Creating nodesDB from /home/lamma/faststorage/scripts/qc_and_filtering/data/nodes.dmp and /home/lamma/faststorage/scripts/qc_and_filtering/data/names.dmp
[+] Parsing tax0 - /home/lamma/faststorage/kasun_amyco/blobtools/PSU4_ISF1A.out
[+] Computing taxonomy using taxrule(s) bestsum
[%] : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64.0/64.0 [00:00<00:00, 7.52kit/s]
[+] Parsing bam0 - /home/lamma/faststorage/kasun_amyco/clean_short-reads_Q30/bwa-generic-output/PSU4_ISF1A.bam
[+] -> 100.00 (64/64) of sequences have reads aligned to them.
[+] -> 0.00 (0/245696) of reads are mapped.
```

This is what I see so far, seems that when inside a slurm job there is issues?

**Comment by DRL** [comment]
so it has parsed the FASTA and the BLAST file without incident and is now looking at the BAM file ...

how big is your BAM file? maybe the SLURM job finished because you hit the ceiling with RAM requirements to parse the BAM file...

**Comment by Lamm-a** [comment]
the BAM file is `5739631`. I am using 60G of RAM in the slurm job. on the command like the HPC really limite our RAM so it seems like it may be a slurm specific issue as the above output printed when running from the command line got much further that in the slurm job?

**Comment by DRL** [comment]
yeah ... could be SLURM thing... never worked with a SLURM cluster so better to ask your local sysadmin to help you out.

If there is a way to login on a node and run things directly, do that. Should work then. Reopen this if not.

Sorry that this was not straightforward ...

cheers,  

dom

**Comment by Lamm-a** [comment]
No worries, at least we seemed to have worked it out!
