### ISSUE TITLE
ModuleNotFoundError: No module named 'docopt'

### ISSUE THREAD

**Issue by RahmatpourNasim** [DRL/blobtools#116]
Hello,
I see this error with create command. Can any one help me with this? I see this issue with both new and old version of blob tools. 
ModuleNotFoundError: No module named 'docopt'

**Comment by Wilsonjsjunior** [comment]
Try install docopt with the same version of python that you install setup.py

ex: 
```
pip3.8 install docopt
python3.8 setup.py install --user
```

**Comment by DRL** [comment]
I would recommend installing dependencies via conda. Using pip often just brings grief.
