### ISSUE TITLE
no taxonomy hits

### ISSUE THREAD

**Issue by clydeandforth** [DRL/blobtools#12]
Hi Dom,

I put my data into blobtools and generated a plot. However, using the blobtools view option the output json file only has no-hit taxonomy matches. I'm not sure why this is happening as a blastn search using my contig Fasta file against the nt/nr database produced taxonomic data;

blastn -task megablast -query GQ13_assembly -db nt  -outfmt '6 qseqid staxids bitscore std sscinames sskingdoms stitle' -culling_limit 5  -evalue 1e-25 -o out

Producing taxonomy hits;

NODE_42_length_38542_cov_0.151908_ID_83 N/A     1393    gi|928489081|gb|CP012685.1|     86.77   1255    161     5
13027   14278   476961  475709  0.0     N/A     N/A     Serratia marcescens strain SmUNAM836, complete genome
NODE_42_length_38542_cov_0.151908_ID_83 N/A     5376    gi|926475601|gb|CP012639.1|     84.48   5515    784     49
16184   21679   940678  946139  0.0     N/A     N/A     Serratia marcescens strain RSC-14, complete genome
N

But when I ran blobtools view I get no-hits at all taxonomic levels in the json file, using this command;

blobtools create -i GQ13_assembly  -y spades -o GQ13_blob --nodes taxdump/nodes.dmp --names taxdump/names.dmp -b 1_sorted.bam -t GQ13_blast_plus   --title fa

producing a lot of;

"species": {"score": 0.0, "tax": "no-hit", "c_index": null}}}

I get a plot but as you would expect there is only no-hits.

I'm not quite sure why the taxonomy annotations aren't making it into blobtools view output?

Thanks,

James

Blobtools downloaded 2 days ago from this site
Blast+ v2.2.31

**Comment by DRL** [comment]
Hi James,

the problem is that your search against nt gave you no taxids, but N/A's ...

> NODE_42_length_38542_cov_0.151908_ID_83 **N/A** 1393 gi|928489081|gb|CP012685.1| 86.77 1255 161 5 13027 14278 476961 475709 0.0 N/A N/A Serratia marcescens strain SmUNAM836, complete genome

there might be something wrong with your blastdb. Have you set $BLASTDB to point to the blastdb directory? 

cheers, 

dom

**Comment by clydeandforth** [comment]
Hi Dom,

I hadn't linked my nr/nt database with tax id. I missed the mapping file, i.e. the taxid_map option,

I re-built the database;

makeblastdb -in nt -parse_seqids -dbtype nucl -taxid_map  taxdump/gi_taxid_nucl.dmp

Now I have taxonomy in the json file;

family": "Enterobacteriaceae", "order": "Enterobacteriales", "phylum": "Proteobacteria",

and a nice plot!

Thanks for your help,

James
