### ISSUE TITLE
Problems with BlobToolKit Viewer

### ISSUE THREAD

**Issue by ejourdai** [DRL/blobtools#125]
Hello,
I am having issues with the blobtool viewer. All steps seem to go fine and I am not having any errors with my blasts or aligning and I can build my blobtools directory with hits and cov, but when I go to https://localhost:8080 to view the interactive BlobToolKit Viewer, I just get an error that says "Dataset true could not be found". Has anyone seen this before?

**Comment by margaretc-ho** [comment]
@ejourdai  you might want to post this issue in blobtoolkit https://github.com/blobtoolkit/blobtoolkit (blobtools v4) since its a different repository than this one (blobtools 1.1.1)
