### ISSUE TITLE
 DocoptExit ImportError: No module named docopt

### ISSUE THREAD

**Issue by Gon1976** [DRL/blobtools#127]
hi
I just installed blobtools and I have this error
.local/lib/python2.7/site-packages/blobtools-1.1-py2.7.egg/lib/interface.py", line 44, in <module>
    from docopt import docopt, DocoptExit
ImportError: No module named docopt

could you help me?
thanks
Gonzalo

**Comment by DRL** [comment]
Looks like you are using python 2.7. That won't work.

You need to install it as described in the readme.

cheers, 

dom

**Comment by Gon1976** [comment]
I use the command as in the readme
Now I try with python3:  python3 setup.py install --user
and observe the same error

>python3 blobtools
Traceback (most recent call last):
  File "blobtools", line 4, in <module>
    from lib.interface import main
  File "/home/installs/blobtools/lib/interface.py", line 44, in <module>
    from docopt import docopt, DocoptExit
ModuleNotFoundError: No module named 'docopt'

**Comment by DRL** [comment]
install the dependencies with 

```
conda create -n blobtools
conda activate blobtools
conda install -c anaconda matplotlib docopt tqdm wget pyyaml git
conda install -c bioconda pysam --update-deps
```
