### ISSUE TITLE
Parsing Mapping file getting Killed

### ISSUE THREAD

**Issue by migueldc1** [DRL/blobtools#133]
Hello,

I'm being unable to parse any database with blobtools taxify. I am following some tutorial for the assembly of MAGs. I have these diamond runs against the uniref90 database, but whenever I try create the taxified output, the progress just gets killed:
```
blobtools taxify -f Diamond/PGL402__FKDN240174132-1A_22C5VCLT4_L8_1_uniref90.diamond -m uniref90.fasta.taxlist -s 0 -t 1 -o blobtools/PGL402__FKDN240174132-1A_22C5VCLT4_L8/PGL402__FKDN240174132-1A_22C5VCLT4_L8_blobtools
[+] Parsing Mapping file - uniref90.fasta.taxlist
Killed
```
The weird part is that I used to be able to run this script. How could I solve this issue or get some log file with more information about the error?

**Comment by DRL** [comment]
Hey @migueldc1 

I would guess this has less to do with blobtools and more with your system. Something has killed the process.

Check your systemlog for why that happened.

cheers, 

dom
