### ISSUE TITLE
conda installation instructions don't work

### ISSUE THREAD

**Issue by mw55309** [DRL/blobtools#134]
Not sure the last time you checked these, but the conda installation instructions don't work (certainly not on a raw ubuntu EC2 instance)

The pysam installation step errors out with "pysam is not in list", and if you remove the dependencies flag, it runs but errors with a load of conflicts.

The pip install instructions also error out with a missing package.

Could we get some updated installation instructions? :D

**Comment by angelovaag** [comment]
I get the same issue, completely

**Comment by angelovaag** [comment]
In an earlier issue a user suggested using "pip install pysam --user" to install pysam. that worked for me

**Comment by zekepuli** [comment]
> pip install pysam --user

That worked for me too. Thanks!

**Comment by mw55309** [comment]
I always think if the answer is "pip" then you don't understand the question 

``` pip install instructions also error out with a missing package.```

**Comment by DRL** [comment]
Hi all, 

I updated the instructions. Reopen if issues persist. 

Good luck.

dom

**Comment by zekepuli** [comment]
> Hi all,
> 
> I updated the instructions. Reopen if issues persist.
> 
> Good luck.
> 
> dom

I have this error when I use the new instalation method and run ```./blobtools create```:

```
Traceback (most recent call last):
  File "../blob_analysis/../blobtools/blobtools", line 4, in <module>
    from lib.interface import main
  File "../blobtools/lib/interface.py", line 44, in <module>
    from docopt import docopt, DocoptExit
ModuleNotFoundError: No module named 'docopt'
```

**Comment by DRL** [comment]
do you have the conda environment activated?

**Comment by zekepuli** [comment]
> do you have the conda environment activated?

Yes, my steps were:

1. 
```
conda create -n blobtools
conda activate blobtools
conda install -c anaconda matplotlib docopt tqdm wget pyyaml git pysam
```

2. Run example of ```./blobtools create```

**Comment by DRL** [comment]
can you copy all the output of conda and blobtools into a file and post that?

**Comment by zekepuli** [comment]
> can you copy all the output of conda and blobtools into a file and post that?

[blob_install.txt](https://github.com/user-attachments/files/16680836/blob_install.txt)

Here's the output. I corrected the installation because you're trying to install pysam using the anaconda channel. But after fixing that, the docopt package is not recognized anyway

**Comment by DRL** [comment]
could it be that you created a python2 environment?

**Comment by zekepuli** [comment]
It seems that I have both Python 2.7.18 and  Python 3.12.3 in the environment. I don't remember if it was the docopt or the pysam package that requires Python=2.7* to be installed in order to work the `blobtools create`

**Comment by DRL** [comment]
None of them should require python2 ... i'd recommend you delete that environment and start again from scratch

**Comment by ramongallego** [comment]
Hi,
I was having the same issue - It can´t install docopt because to comply with previous packages it has to downgrade to python2. In my case it worked if I force the conda enviroment to be 3.6, but not higher.
