### ISSUE TITLE
DIAMOND output integration

### ISSUE THREAD

**Issue by kthlnktng** [DRL/blobtools#14]
Hi Blobtools developers, 

I would like to create a blobplot using DIAMOND output. In the usage statement of the script for DIAMOND output conversion ([daa_to_tagc.pl](https://github.com/GDKO/CGP-scripts/blob/master/scripts/daa_to_tagc.pl)), it mentions using 'uniref.100.taxlist'. I assume this is contained [here.](https://github.com/GDKO/uniref_taxlist)

Can you describe how the uniref.100.taxlist was created? What version of UniRef 100 was used? I would like to incorporate taxonomy, but do not know if this is possible if I am using a different version of UniRef 100.

**Comment by DRL** [comment]
That is now explained in the documentation
