### ISSUE TITLE
Using standard setuptools for package instalalation

### ISSUE THREAD

**Issue by mmokrejs** [DRL/blobtools#15]
Hi,
  would you mind using setuptools to install your files site-wide? It seemed all *.py should be placed to /usr/bin but that does not work because ./lib/ is missing.

```
$ /usr/bin/covplot.py
Traceback (most recent call last):
  File "/usr/bin/covplot.py", line 47, in <module>
    import lib.BtCore as bt
ImportError: No module named lib.BtCore
$
```
Thank you

**Comment by DRL** [comment]
Hi mmokrejs,

I will look into it. 

Was it not possible for you to install blobtools using virtualenv?

cheers, 

dom

**Comment by mmokrejs** [comment]
Hi,
  I am sorry, I haven't even tried. I always try to install apps into a system-wide location as a package ... I use Gentoo Linux and typically create a package definition file so that the application is installed through standard package manager. And, although one could define the procedure manually, it is easier if the package uses setuptools -- it is then very simple. I am sure other will appreciate this as well.

**Comment by mmokrejs** [comment]
I think it would be helpful to restructure the code so that the importable modules were installed in some standard path where python can find them. Looking for them in ./lib/ is too bad.
