### ISSUE TITLE
Blobtools goes straight to help

### ISSUE THREAD

**Issue by bobbieshaban** [DRL/blobtools#16]
Hi,

I am trying to use blobtools and for the life of me I can't get it to get passed the help screen.

$ python create.py -i transcript-60_clean.fa -t blobplot.txt -x bestsum --nodes /Databases/Database/taxBlastdb/nodes.dmp --names /Databases/Database/taxBlastdb/names.dmp -b blobology.out.bam  -y spades
usage: blobtools create     -i FASTA [-y FASTATYPE] [-o OUTFILE] [--title TITLE]
                              [-b BAM...] [-s SAM...] [-a CAS...] [-c COV...]
                              [--nodes <NODES>] [--names <NAMES>] [--db <NODESDB>]
                              [-t TAX...] [-x TAXRULE...]
                              [-h|--help]

I've even put bestsum in quotes, can you please help me with what I am doing wrong? I'm sure I must have a typo somewhere. 

If I try blobtools create I get the following python error.

 ./blobtools create -i transcript-60_clean.fa -t blobplot.txt -x "bestsum" --nodes /Databases/Database/taxBlastdb/nodes.dmp --names /Databases/Database/taxBlastdb/names.dmp -b blobology.out.bam  -y spades
Traceback (most recent call last):
  File "./create.py", line 36, in <module>
    import lib.BtCore as bt
  File "~/lib/BtCore.py", line 97
    'dict_of_blobs' : {name : blObj.**dict** for name, blObj in self.dict_of_blobs.items()},
                                               ^
SyntaxError: invalid syntax

I am using python 2.7
$ python -V
Python 2.7.8

**Comment by DRL** [comment]
Hi, 
are you running the latest version https://github.com/DRL/blobtools/releases/tag/v0.9.16 ?

```create``` is executed by typing:
```
./blobtools create ...
```
the command below should work
```
./blobtools create \
-i transcript-60_clean.fa \
-t blobplot.txt \
-x bestsum \
--nodes /Databases/Database/taxBlastdb/nodes.dmp \
--names /Databases/Database/taxBlastdb/names.dmp \
-b blobology.out.bam \
-y spades
```

cheers, 

dom

**Comment by bobbieshaban** [comment]
Hi,

Pretty sure I have the latest version, I git a syntax error after running that command.

[shabanb@melb-compute04 git]$ python27 ./blobtools create -i transcript-60_clean.fa -t blobplot.txt -x bestsum --nodes /Databases/Database/taxBlastdb/nodes.dmp --names /Databases/Database/taxBlastdb/names.dmp -b blobology.out.bam -y spades
Traceback (most recent call last):
  File "./create.py", line 36, in <module>
    import lib.BtCore as bt
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/blobTools/git/lib/BtCore.py", line 97
    'dict_of_blobs' : {name : blObj.__dict__ for name, blObj in self.dict_of_blobs.items()},
                                               ^
SyntaxError: invalid syntax

**Comment by ksdiaz** [comment]
I just had this happen to me as well.  I ran it earlier today and it worked fine, but on a second pipeline through, with the same BLAST taxfile, just filtered to remove low-confidence hits, blobtools is going straight to help on the _blobtools view_ command.  It executed _blobtools create_ just fine. I have the latest version, but no errors occur at all, just straight to the help output.  _blobplot_ also executes just fine.

**Comment by DRL** [comment]
Hi,
you are both not executing the programs as described in the manual. 
Please execute it as specified in the manual and let me know if the problem persists.

cheers, 

dom

**Comment by ksdiaz** [comment]
As far as I can tell, I've been running it exactly as described in the manual.  Is there an obvious error I made that I can't spot?  I did get it running the first time, and when I repeated the command after that, I have been getting the straight-to-help "error" screen.  

Thank you!

**Comment by DRL** [comment]
Hi ksfiaz,

execute "blobtools create" like this: ```./blobtools create````

not like this: ```python create.py``` or ```python blobtools```

cheers, 

dom

**Comment by ksdiaz** [comment]
That was how I first encountered the error.  I tried running it directly via the python script to see if I could debug it, but I couldn't figure out where the issue lay.  When I run `./blobtools create` I have no problem getting a BlobDB file, but when I run `./blobtools view`  I just get the help screen, even if I run all defaults and only input the BlobDB file.
