### ISSUE TITLE
matplotlib future warning

### ISSUE THREAD

**Issue by JohnUrban** [DRL/blobtools#20]
Hi,

Thanks for the great set of tools.

I just started using blobtools, but I have seen this message twice when doing `blobtools blobplot`:
```
/users/jurban/software/localpy/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
```

Not sure if it is affecting anything, but thought I'd pass it along.

best,

  John

**Comment by JohnUrban** [comment]
Let me try matplotlib 1.5 - before continuing with this thread.

**Comment by JohnUrban** [comment]
I think that did the trick, though I got another message:
```
UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
```

**Comment by DRL** [comment]
Hi JohnUrban,
yes, correct. blobtools needs matplotlib1.5.

the thing about the fonts is that matplotlib has to generate them the first time it wants to use them. 

you can find more info [here](https://github.com/matplotlib/matplotlib/issues/5836)

cheers, 

dom
