### ISSUE TITLE
Span in blobplot ?

### ISSUE THREAD

**Issue by ptranvan** [DRL/blobtools#23]
Hello,

When plotting the blobplot: what does mean the "Span (kb)" on Y axis (top figure)?

**Comment by DRL** [comment]
Hi, 

sorry for taking so long to respond. 

Span (kb) means how much assembly-length (in kilobases) are placed in each bin of the histogram. In other words, the histogram is weighted by the length of the contigs.

this behaviour can be changed using ```[--hist count]```, which plots un-weighted histograms.  

hope this helps.

cheers, 

dom
