### ISSUE TITLE
In blobtools view tabular output, what does .c indicate?

### ISSUE THREAD

**Issue by sujaikumar** [DRL/blobtools#25]
Someone asked this because it wasn't clear in the README (or in the output)

Columns like phylum.c or order.c are not described properly on the github page, but they show the confusion-index - how many other taxa did it hit at that tax level (eg Phylum).
None indicates no hit
0 indicates no confusion (all hits were to one phylum, or whichever tax-level was chosen)
1 indicates one other phylum was hit
2 indicates 2 other phyla were hit, and so on

Can you please add this in the README or in the help text of blobtools view? Thanks!

**Comment by DRL** [comment]
I am in the process of updating the documentation. Will add this.

cheers, 

dom
