### ISSUE TITLE
Mapping file advice

### ISSUE THREAD

**Issue by ptranvan** [DRL/blobtools#40]
Hi,

First I would like to produce a mapping file for coverage estimation and then plot a blobplot.

For removing contaminations, I will select the contigs that have been assigned to the desire organisms and mapped my initial reads to those contigs.

Do you have any advice for the mapping file (parameter etc.)?

I'm using bwa mem but I'm wondering whether I should use the -m option (discard reads mapping to multiple locations)

**Comment by DRL** [comment]
Hi ptranvan,

Blobtools uses only reads that pass the following samflags

```samtools view -f 1 -F 1024 -F 256 -F 2048``` 

so you shouldn't have to worry about multimappings .
