### ISSUE TITLE
division by zero when creating

### ISSUE THREAD

**Issue by ishengtsai** [DRL/blobtools#48]
Hi, 

I was running blobtools but failed at first stage:

`/home/ijt/bin/blobtools/blobtools create -i ref.fa -b 180bp-pe.sorted.bam -t assembly.vs.uniref90.dmnd -o first`

and

`Traceback (most recent call last):
  File "/home/ijt/bin/blobtools/bloblib/create.py", line 115, in <module>
    main()
  File "/home/ijt/bin/blobtools/bloblib/create.py", line 108, in main
    blobDb.parseCoverage(covLibObjs=cov_libs, no_base_cov=None, prefix=prefix)
  File "/home/ijt/bin/blobtools/bloblib/BtCore.py", line 355, in parseCoverage
    cov = base_cov / self.dict_of_blobs[name].agct_count
ZeroDivisionError: division by zero`

Any suggestions would be great!

**Comment by DRL** [comment]
Hi ishengtsai,

could it be that you have an empty sequence in your assembly file?

cheers, 

dom

**Comment by kaylahardwick** [comment]
Hello,

I'm just wondering if this issue was ever resolved? I got the same error, and I don't have any empty sequences in my assembly file. 

Thanks in advance for your help!

**Comment by DRL** [comment]
Hi kaylahardwick,

this happens when either the bam file is empty or you have empty sequences (composed of N's alone0 in your fasta.

if this persist please send me a dropbox link to your files and the command you ran, so I can reproduce the error.

cheers, 

dom

**Comment by theshowmustgolangon** [comment]
it's still happening, and I check the scaffold where it stops with this error. The part has normal sequences with normal bases. Is it solved?
