### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by peterthorpe5** [DRL/blobtools#49]
Hi Dom,

This is not an issue, but for the Virtual environment:
virtualenv -p python2.7 ~/virtualenvs/blobtools

It would be good to add the python 2.7 specifically. 

And this command in the installation:
/blobtools create \
-i test_files/assembly.fna \
-c test_files/mapping_1.bam.cov \
-t test_files/blast.out \
--names names.dmp \
--nodes nodes.dmp

Should have a ./blobtools create?

Pete

**Comment by DRL** [comment]
Hi Pete, 

this is all fixed now with the new installation script.

cheers, 

dom
