### ISSUE TITLE
Error 19

### ISSUE THREAD

**Issue by amm94** [DRL/blobtools#50]
Hi,

I am trying to run blobtools on my data and have run into the following error:
[ERROR:19]	: Sequence Calcutta in file /home/s1670484/Hill_contigs_blast.o2727632 is not part of the assembly.

What should I interpret from this error?

Thank you in advance.
Best regards,
Andrea

**Comment by DRL** [comment]
Hi, 

sorry for not replying earlier. Are you sure you provided a correct BLAST file?

cheers, 

dom

**Comment by amm94** [comment]
Hi, I managed to solve it a few weeks ago, I was providing an input file with messed up data. Somehow I finally got it working!Thanks for your reply,AndreaOn 10 Jul 2017 10:06 p.m., Dominik R Laetsch <notifications@github.com> wrote:Hi,
sorry for not replying earlier. Are you sure you provided a correct BLAST file?
cheers,
dom

**Comment by DRL** [comment]
Ok, let me know if you run into any other problems.

cheers, 

dom
