### ISSUE TITLE
Rank: kingdom?

### ISSUE THREAD

**Issue by apelin20** [DRL/blobtools#58]
Hello,

I find the rank phylum most useful to me, but even then often I need to look up many of the phyla to realize what kingdom the taxonomy belongs to.

I would suggest adding a rank for kingdom, fungi, plants, animals....

Rank order and family seem to generate the same output.

Thanks,
Adrian

**Comment by DRL** [comment]
Hi Adrian, 

the next major version will include all possible taxonomic ranks.

cheers, 

dom
