### ISSUE TITLE
Feature request: Access to ggplot2 R object

### ISSUE THREAD

**Issue by fennerm** [DRL/blobtools#67]
It would be nice if blobtools plot and blobtools covplot had flags which allowed the user to access the underlying R plot objects so that they could be further edited. E.g in order to add lines which show filter criteria, or to hide certain groups without having to filter the bam file. 

This would be fairly easy to achieve by just outputting an Rds file, I'd be happy to implement in a pull request if you're game.

**Comment by DRL** [comment]
Hi fennerm,

BlobTools is written in Python and afaik there is no easy way of turning Python matplotlib objects into R objects...

However, hiding of certain groups can easily be achieved using the ```--exclude``` flag. And regarding subsequent editing of the plot, I usually edit PDFs using Inkscape or Adobe Illustrator.

Hope that helps.

cheers, 

dom
