### ISSUE TITLE
Which version NCBI nt database is recommenced for a plant genome

### ISSUE THREAD

**Issue by drashutosh** [DRL/blobtools#71]
Hi Dom
I am working  on a plant genome and intended to use blobtools as one of the  filtering steps in my pipeline.
So far I did some blast run using **`NCBI nt`** database and produced blobplots for those run.
I used `nt. 26` as a random database in my blast search.

It is `57 nt database `version in the  [ftp://ftp.ncbi.nlm.nih.gov/blast/db/](url) 

What version would suggest to use for getting better results with blobtools?

Thanks in advance 

Ashuttosh

**Comment by DRL** [comment]
Hi Ashuttosh,

if you want to blast against NCBI nt, you need to download all 58 files (nt.00.tar.gz - nt.57.tar.gz) for the pre-formatted blast database. The individual files are not versions, but parts of the same database. 

hope that helps, 

dom
