### ISSUE TITLE
Missing "module named req"

### ISSUE THREAD

**Issue by kmdowney12** [DRL/blobtools#72]
I'm installing Blobtool v1.0 and I keep getting this error thrown back at me following the ./install command.

[+] Checking dependencies...
    [+] [wget] /usr/local/bin/wget
    [+] [tar] /usr/bin/tar
    [+] [pip] pip
    [+] [python2.7] /Users/kdowney/anaconda3/envs/blob_tools/bin/python
[+] Installing python dependencies...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from pip.req import parse_requirements
ImportError: No module named req
FAIL.

What can I do to fix this? There are some tips online, but when I modify your code as they recommend, other pieces start failing.

**Comment by kmdowney12** [comment]
Also, I'm doing this on a Mac if that matters.

**Comment by DRL** [comment]
Hi, 

sorry for not answering earlier ... 

I guess you already noticed that this was caused by your python being python3 instead of python2...

cheers, 

dom

**Comment by kmdowney12** [comment]
Hi Dom,

Nope, my python was fine. We just switched it over to our Linux machine
instead. Works fine there. Thanks though!

Kala Downey
Research Assistant
Doctoral Student (Alverson Lab)
University of Arkansas-Fayetteville
kmdowney@email.uark.edu

On Mon, May 28, 2018 at 8:42 AM, Dominik R Laetsch <notifications@github.com

**Comment by DRL** [comment]
Ahso, ... I thought the **anaconda3** in your python path meant it was a python3 environment.

let me know if you run into any other problems.

cheers, 

dom

**Comment by TomHarrop** [comment]
Hallo @DRL, I also had this issue using pip 18.0 with python 2.7.15 on Debian 9.5 (stretch) 

```
~/blobtools> which pip
/usr/local/bin/pip
~/blobtools> /usr/local/bin/pip --version
pip 18.0 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
~/blobtools> which python
/usr/local/bin/python
~/blobtools> /usr/local/bin/python --version
Python 2.7.15
```
It looks like `from pip.req import parse_requirements` doesn't work with `pip > 10`, see: https://stackoverflow.com/a/49867265

Workaround is to downgrade to pip 9 e.g.

```
python -m pip install pip==9.0.3
```
Cheers!
