### ISSUE TITLE
blobtools plot: __init__() got an unexpected keyword argument 'fontsize'

### ISSUE THREAD

**Issue by cg449** [DRL/blobtools#8]
Hello, thanks for making this great software! I am using it for the first time, and I tried plotting my BlobDB.json file using this command:

blobtools plot -i /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.BlobDB.json -p 14 --out Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499

Here is the error message I received:

[STATUS]	: Reading BlobDb /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.BlobDB.json
	[INFO]	: no-hit : sequences = 156,883, span = 181.24 MB, N50 = 1,333 nt
Traceback (most recent call last):
  File "/Users/cg449/Applications/blobtools/plot.py", line 183, in <module>
    plotObj.plotBlobs(cov_lib, info_flag)
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 606, in plotBlobs
    plot_ref_legend(axScatter)
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 191, in plot_ref_legend
    axScatter.legend([ref_1,ref_2,ref_3], ["1,000nt", "5,000nt", "10,000nt"], numpoints=1, loc = 4, fontsize=FONTSIZE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 4519, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fontsize'

Can you tell me what is wrong? I noticed that "fontsize=FONTSIZE" appeared many times in Btplot.py script, when maybe it should have been fontsize=35 or some other number. Thanks.

**Comment by DRL** [comment]
Hi, 

> Can you tell me what is wrong? I noticed that "fontsize=FONTSIZE" appeared many times in Btplot.py script, when maybe it should have been fontsize=35 or some other number. Thanks.

I am not sure what's wrong ... the "fontsize=FONTSIZE" bit should not be a problem since FONTSIZE gets declared at the top of BtPlot.py (and when I tested the last release it did not give a problem).

Could you 
- look whether "blobtools view" works on the BlobDb?
- check that you have the latest release?

cheers, 
dom

**Comment by cg449** [comment]
Hi Dom,

Thanks for your quick reply. I deleted my existing blobtools folder and re-cloned blobtools from GitHub.

I re-ran the blobtools plot command and got the same error:

Command:
blobtools plot -i /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.BlobDB.json -p 14 --out Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499

Output:
[STATUS]	: Reading BlobDb /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.BlobDB.json
	[INFO]	: no-hit : sequences = 156,883, span = 181.24 MB, N50 = 1,333 nt
Traceback (most recent call last):
  File "/Users/cg449/Applications/blobtools/plot.py", line 183, in <module>
    plotObj.plotBlobs(cov_lib, info_flag)
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 608, in plotBlobs
    plot_ref_legend(axScatter)
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 190, in plot_ref_legend
    axScatter.legend([ref_1,ref_2,ref_3], ["1,000nt", "5,000nt", "10,000nt"], numpoints=1, loc = 4, fontsize=FONTSIZE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 4519, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fontsize'

Blobtools view ran without error, but it gave me an output file with no phylum hits. I just realized that maybe it was because my "--taxfile" that I fed to blobtools create was in the blast output format that had "qseqids" and "staxids", but not the bitscore. Do you think that might be causing the error? I can re-do the BLAST run and try again. There is one thing I don't understand- why does the Blobtools paper recommend we use a random subset of contigs to save time during the BLAST run? How can all the contaminants be removed if they aren't all used as queries during the BLAST run?

Thanks so much,
Christy 


P.S. Blobtools view output:

	##
## assembly : /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Trinity_Tdactyloides_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.fasta
## bam0 : /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Trinity_Tdactyloides_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.fasta.Tdactyloides2_no_rRNA.bowtie2.bam
## tax0 : /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/random10k.Trinity_Tdactyloides_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.fasta.nt.1e-5.megablast
## nodesDB : /Users/cg449/Applications/blobtools/data/nodesDB.txt
## taxrule : bestsum
##
# name	length	GC	N	bam0	phylum.t	phylum.s	phylum.c
TR12|c1_g1_i1	576	0.4028	0	0.996527777778	no-hit	0.0	None	
TR14|c0_g1_i1	776	0.5399	0	13.3131443299	no-hit	0.0	None	
TR39|c0_g1_i1	610	0.5066	0	64.0655737705	no-hit	0.0	None	
TR58|c0_g1_i1	531	0.5499	0	4.66854990584	no-hit	0.0	None	
TR82|c0_g1_i1	540	0.5407	0	2.6537037037	no-hit	0.0	None	
TR91|c0_g1_i1	663	0.5822	0	5.69079939668	no-hit	0.0	None

**Comment by cg449** [comment]
Hi Dom,

I re-ran the blast against the nt database with my entire transcriptome dataset with the flag -outfmt '6 qseqid staxid bitscore'. I then ran blobtools create with the newest version of blobtools, and then blobtools plot. I still get that fontsize error:

Command:

blobtools plot -i /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides4_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.BlobDB.json -p 14 --out Tdactyloides4_no_roots_no_normalization_min_kmer_cov_2_greater_than_499

Output:

[STATUS]	: Reading BlobDb /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides4_no_roots_no_normalization_min_kmer_cov_2_greater_than_499.BlobDB.json
	[INFO]	: Streptophyta : sequences = 124,919, span = 154.69 MB, N50 = 1,453 nt
	[INFO]	: no-hit : sequences = 21,939, span = 17.96 MB, N50 = 807 nt
	[INFO]	: Ascomycota : sequences = 4,143, span = 3.55 MB, N50 = 879 nt
	[INFO]	: Chordata : sequences = 3,332, span = 2.91 MB, N50 = 896 nt
	[INFO]	: Arthropoda : sequences = 2,311, span = 1.94 MB, N50 = 828 nt
	[INFO]	: Eukaryota-undef : sequences = 32, span = 0.03 MB, N50 = 793 nt
	[INFO]	: Nematoda : sequences = 23, span = 0.03 MB, N50 = 960 nt
	[INFO]	: Actinobacteria : sequences = 16, span = 0.02 MB, N50 = 2,120 nt
	[INFO]	: Platyhelminthes : sequences = 26, span = 0.02 MB, N50 = 744 nt
	[INFO]	: Annelida : sequences = 26, span = 0.02 MB, N50 = 659 nt
	[INFO]	: Proteobacteria : sequences = 22, span = 0.02 MB, N50 = 748 nt
	[INFO]	: Bacteroidetes : sequences = 21, span = 0.01 MB, N50 = 716 nt
	[INFO]	: Bacteria-undef : sequences = 13, span = 0.01 MB, N50 = 1,011 nt
	[INFO]	: undef : sequences = 16, span = 0.01 MB, N50 = 659 nt
	[INFO]	: other : sequences = 44, span = 0.03 MB, N50 = 723 nt
Traceback (most recent call last):
  File "/Users/cg449/Applications/blobtools/plot.py", line 183, in <module>
    plotObj.plotBlobs(cov_lib, info_flag)
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 608, in plotBlobs
    plot_ref_legend(axScatter)
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 190, in plot_ref_legend
    axScatter.legend([ref_1,ref_2,ref_3], ["1,000nt", "5,000nt", "10,000nt"], numpoints=1, loc = 4, fontsize=FONTSIZE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 4519, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fontsize'

What do you recommend I do to get past this error?

Thanks,
Christy

**Comment by DRL** [comment]
Hi Christy, 
sorry for not getting back earlier ...

Which version of matplotlib are you using?

could you run :

    pip freeze | grep matplotlib

cheers, 

dom

**Comment by cg449** [comment]
Hi, 

That's OK thanks for helping!

I ran this command: pip freeze | grep matplotlib

Result:

/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
matplotlib==1.1.1

**Comment by DRL** [comment]
Hi Christy, 

this is most likely the problem, matplotlib 1.5 is required for running blobtools.

You could install "virtual env" in order to have a separate python environment so you can install matplotlib 1.5 and docopt independently for your main python installation
```
# install virtualenv 
pip install virtualenv

# clone blobtools into folder
git clone https://github.com/DRL/blobtools.git

# create virtual environment for blobtools  
cd blobtools/
virtualenv blob_env

# activate virtual environment
source blob_env/bin/activate

# install matplotlib
(blob_env) $ pip install matplotlib

# install docopt
(blob_env) $ pip install docopt 

# run
(blob_env) $ ./blobtools -h
```

**Comment by cg449** [comment]
Hello,

It still isn't working, even in the virtual environment. However, it is giving me a different error, which I suppose is progress. The error I get when I run blobtools plot is now: "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)". Below is my entire string of commands and their output, and blobtools plot is the last command. Any help would be greatly appreciated! Thanks.

Command: 
virtualenv blob_env3

Output:
New python executable in blob_env3/bin/python
Installing setuptools, pip, wheel...done.

Command:
source blob_env3/bin/activate

Command (to try and solve the constant InsecurePlatformWarning I was getting):
pip install --upgrade ndg-httpsclient

Output:
Collecting ndg-httpsclient
/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting PyOpenSSL (from ndg-httpsclient)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting six>=1.5.2 (from PyOpenSSL->ndg-httpsclient)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from PyOpenSSL->ndg-httpsclient)
  Using cached cryptography-1.2.1-cp27-none-macosx_10_6_intel.whl
Collecting enum34 (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
Collecting ipaddress (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting setuptools>=1.0 (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Using cached setuptools-19.2-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Using cached cffi-1.4.2-cp27-none-macosx_10_6_intel.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
Installing collected packages: six, enum34, ipaddress, pyasn1, setuptools, idna, pycparser, cffi, cryptography, PyOpenSSL, ndg-httpsclient
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed PyOpenSSL-0.15.1 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 idna-2.0 ipaddress-1.0.16 ndg-httpsclient-0.4.0 pyasn1-0.1.9 pycparser-2.14 setuptools-19.2 six-1.10.0

Command (to try and solve the constant InsecurePlatformWarning I was getting):
pip install pyopenssl ndg-httpsclient pyasn1

Output:
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in ./blob_env3/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in ./blob_env3/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in ./blob_env3/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in ./blob_env3/lib/python2.7/site-packages (from pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in ./blob_env3/lib/python2.7/site-packages (from pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): enum34 in ./blob_env3/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in ./blob_env3/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in ./blob_env3/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in ./blob_env3/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in ./blob_env3/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl)
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./blob_env3/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=0.7->pyopenssl)
(blob_env3)rs-btcg449lt:blobtools cg449$ pip install matplotlib
Collecting matplotlib
  Using cached matplotlib-1.5.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.6 (from matplotlib)
  Using cached numpy-1.10.4-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pytz (from matplotlib)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Collecting cycler (from matplotlib)
  Using cached cycler-0.9.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,>=1.5.6 (from matplotlib)
  Using cached pyparsing-2.0.7-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./blob_env3/lib/python2.7/site-packages (from python-dateutil->matplotlib)
Installing collected packages: numpy, pytz, python-dateutil, cycler, pyparsing, matplotlib
Successfully installed cycler-0.9.0 matplotlib-1.5.1 numpy-1.10.4 pyparsing-2.0.7 python-dateutil-2.4.2 pytz-2015.7

Command:
pip install docopt

Output:
Collecting docopt
Installing collected packages: docopt
Successfully installed docopt-0.6.2

Command:
blobtools plot -i /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499_virtualenv.BlobDB.json -p 14 --out Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499_virtualenv
/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/Users/cg449/Applications/blobtools/plot.py", line 57, in <module>
    import lib.BtPlot as BtPlot
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/textpath.py", line 15, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1421, in <module>
    _rebuild()
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1406, in _rebuild
    fontManager = FontManager()
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1044, in __init__
    self.ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/font_manager.py", line 324, in findSystemFonts
    for f in get_fontconfig_fonts(fontext):
  File "/Users/cg449/Applications/blobtools/blob_env3/lib/python2.7/site-packages/matplotlib/font_manager.py", line 276, in get_fontconfig_fonts
    stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by DRL** [comment]
Hi Christy, 

could it be that the error messages are incomplete (e.g there is a closing bracket in the fifth line from the bottom that does not have an opening bracket). It is very hard to figure out what's going on without having all information.

Can you sent me the last part again? Also, what OS version are you using? Have you checked that matplotlib 1.5.1 is now installed correctly (using pip freeze)? 

cheers,

dom

**Comment by cg449** [comment]
Hello,

I'm not sure why that closing bracket is missing. It looks that way in my terminal as well. I ran everything again and I'm just going to copy and paste my entire terminal here so you can see it. As it says below, I am running matplotlib 1.5.1 in the virtual environment. I am using OS X 10.9.5. 

Here is all the text from my terminal, unedited:

rs-btcg449lt:blobtools cg449$ virtualenv blob_env4
New python executable in blob_env4/bin/python
Installing setuptools, pip, wheel...done.
rs-btcg449lt:blobtools cg449$ source blob_env4/bin/activate
(blob_env4)rs-btcg449lt:blobtools cg449$ pip install matplotlib
Collecting matplotlib
/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached matplotlib-1.5.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.6 (from matplotlib)
  Using cached numpy-1.10.4-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pytz (from matplotlib)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Collecting cycler (from matplotlib)
  Using cached cycler-0.9.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,>=1.5.6 (from matplotlib)
  Using cached pyparsing-2.0.7-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->matplotlib)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: numpy, pytz, six, python-dateutil, cycler, pyparsing, matplotlib
Successfully installed cycler-0.9.0 matplotlib-1.5.1 numpy-1.10.4 pyparsing-2.0.7 python-dateutil-2.4.2 pytz-2015.7 six-1.10.0
/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
(blob_env4)rs-btcg449lt:blobtools cg449$ pip freeze | grep matplotlib
matplotlib==1.5.1
(blob_env4)rs-btcg449lt:blobtools cg449$ pip install docopt
Collecting docopt
/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Installing collected packages: docopt
Successfully installed docopt-0.6.2
(blob_env4)rs-btcg449lt:blobtools cg449$ ./blobtools plot -i /Users/cg449/Desktop/Tripsacum/transcriptome_assembly/Tdactyloides/Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499_virtualenv.BlobDB.json -p 14 --out Trinity_assembly_no_root_libraries/Tdactyloides2_no_roots_no_normalization_min_kmer_cov_2_greater_than_499_virtualenv_blobplot
/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "./plot.py", line 57, in <module>
    import lib.BtPlot as BtPlot
  File "/Users/cg449/Applications/blobtools/lib/BtPlot.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/textpath.py", line 15, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1421, in <module>
    _rebuild()
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1406, in _rebuild
    fontManager = FontManager()
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1044, in __init__
    self.ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/font_manager.py", line 324, in findSystemFonts
    for f in get_fontconfig_fonts(fontext):
  File "/Users/cg449/Applications/blobtools/blob_env4/lib/python2.7/site-packages/matplotlib/font_manager.py", line 276, in get_fontconfig_fonts
    stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
(blob_env4)rs-btcg449lt:blobtools cg449$

**Comment by cg449** [comment]
I noticed that the bold "init" in the error message is surrounded by two underscores on either side in my terminal, but it isn't showing up right when I paste it. For some reason, the github website is converting the text that looks like "underscore underscore init underscore underscore" into simply a bold init. I only noticed because it was in the line of the error message you were referring to that looked incomplete. Actually, now that I look closer, a lot of text in the error message is getting converted to special fonts like italics when I past them into the website.

I attached a text document of the error, to get around this communication problem:

[blobology_error.txt](https://github.com/DRL/blobtools/files/92492/blobology_error.txt)

**Comment by timregan** [comment]
Hi there,
I am also encountering an error with the Font building matplotlib (It is the newer 1.5.1 version which I have installed).
Error reads as follows:

Traceback (most recent call last):
  File "./plot.py", line 57, in <module>
    import lib.BtPlot as BtPlot
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/lib/BtPlot.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/textpath.py", line 15, in <module>
    import matplotlib.font_manager as font_manager
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1421, in <module>
    _rebuild()
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1408, in _rebuild
    pickle_dump(fontManager, _fmcache)
  File "/mnt/ris-fas1a/linux_groups2/freeman_grp/Blobs/blobtools/blob_env/lib/python2.7/site-packages/matplotlib/font_manager.py", line 957, in pickle_dump
    pickle.dump(data, fh)
IOError: [Errno 122] Disk quota exceeded

In the case that this is also coming up as special text, attached is a text file of the error.
[Blobs Error.txt](https://github.com/DRL/blobtools/files/94200/Blobs.Error.txt)

**Comment by DRL** [comment]
Hi,

these errors are due to problems with the matplotlib installation.

cheers, 

dom
