### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by colindaven** [DRL/blobtools#81]
Hi,

I'm interested in this package but will not be installing it since support for python 2.7 will be removed by 2020. Much scientific software will then have to be updated or become obsolete. Are there any plans to move the codebase to Python3 ?

Thanks.
Colin

**Comment by cschu** [comment]
@colindaven, have a look at my fork (cschu/blobtools). I just ported blobtools to Python3 (also decoupled from samtools version 1.5 (samtools needs to be in the PATH). I have tested it with the example data, which seems to work fine. In the coming days I'll probably be able to test it further with more data and then I'd create a PR. If you want to test it, please have a go.

**Comment by DRL** [comment]
Hi both,

upcoming release will be python3. 

cheers, 

dom

**Comment by colindaven** [comment]
Thanks for this - sorry, didn't get a chance to test. I work in a core unit and things are crazy from Nov-March, but subside a bit (I hope) over summer.
