### ISSUE TITLE
error in uniprot parallel download

### ISSUE THREAD

**Issue by raw937** [DRL/blobtools#87]
# Download database
#wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/Reference_Proteomes_2019_02.tar.gz

# Unpack protein FASTAs for each kingdom
parallel -j4 'gunzip {}' ::: `ls | grep "fasta.gz" | grep -v 'DNA' | grep -v 'additional'

The unpacking of fasta's isn't working. 
/var/spool/slurmd/job8046023/slurm_script: line 18: unexpected EOF while looking for matching ``'
/var/spool/slurmd/job8046023/slurm_script: line 33: syntax error: unexpected end of file

Any thoughts?

**Comment by kate-stankiewicz** [comment]
I am having the same issue. Did you find a fix?

**Comment by DRL** [comment]
Could be that you did not download the complete file...

I would look at what is happening in line 18 and 33 of your slurm script...

cheers, 

dom
