### ISSUE TITLE
blobtools create tool error

### ISSUE THREAD

**Issue by XClaws** [DRL/blobtools#92]
Dear team.
I have encountered a error during blobtools create for example, here is the error report.

python blobtools.py create  \
-i example/assembly.fna  \
-b example/mapping_1.bam  \
-t example/blast.out  \
-o example/my_first_blobplot
[+] Parsing FASTA - example/assembly.fna
[ERROR:28]      : Please specify "--names" and "--nodes", or "--db"

**Comment by lukesarre** [comment]
I am experiencing this problem. Has anyone found a solution?

**Comment by DRL** [comment]
Hi,

maybe it's the wrong python executable.

And maybe better to run it as 

```
./blobtools create
-i example/assembly.fna
-b example/mapping_1.bam
-t example/blast.out
-o example/my_first_blobplot
```
cheers, 

dom

**Comment by fhbvl** [comment]
I had the same issue when downloading blobtools from the release page. In the release version the NCBI nodeDB is not included. So you need to do the steps provided in the documentation by yourself ("Download NCBI taxdump and create nodesdb"). This way a default database is created and can be used by the script.
